version: '1.0'
name: pipeline-20220630
displayName: pipeline-20220630
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-e64edf76
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./dist && npm run build:site
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        strategy:
          retry: '0'
  - name: stage-dc7a1efe
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID: jolyne
        deployArtifact:
          - source: build
            name: dist
            target: /home/static-site/jolyne-ui
            dependArtifact: BUILD_ARTIFACT
        script: |-
          cd /home/static-site/jolyne-ui
          tar -zxvf dist.tar.gz
          echo 'Hello Gitee!'
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
